import initiAddClass from "./modules/add-class.js";
import initiMovimentoPeaoBranco from "./modules/movimento-peao-branco.js";
import initiMovimentoPeaoPreto from "./modules/movimento-peao-preto.js";
import initiMovimentoGeral from "./modules/movimento-geral.js";
import initiMovimentoBispo from "./modules/movimento-bispo.js";
import initiMovimentoBispo2 from "./modules/movimento-bispo2.js";
import initiMovimentoTorre from "./modules/movimento-torre.js";
import initiMovimentoTorre2 from "./modules/movimento-torre2.js";
//import initiMovimentoRainha from "./modules/movimento-rainha.js";
//import initiMovimentoRainha2 from "./modules/movimento-rainha2.js";
//import initiMovimentoRainha3 from "./modules/movimento-rainha3.js";
//import initiMovimentoRainha4 from "./modules/movimento-rainha4.js";
import initiMovimentoCaptura from "./modules/movimento-captura.js";
import initiMovimentoCavalo from "./modules/movimento-cavalo.js";
import initiMovimentoRei from "./modules/movimento-rei.js";
initiAddClass();
initiMovimentoPeaoBranco();
initiMovimentoPeaoPreto();
initiMovimentoGeral();
initiMovimentoBispo();
initiMovimentoBispo2();
initiMovimentoTorre();
initiMovimentoTorre2();
//initiMovimentoRainha();
//initiMovimentoRainha2();
//initiMovimentoRainha3();
//initiMovimentoRainha4();
initiMovimentoCaptura();
initiMovimentoCavalo();
initiMovimentoRei();
/* Quando o span tiver a classe ativo a div irar fazer um loop com for e serar adiconado a classe ativo de acordo com a peça no span */
